FROM node:alpine as builder
WORKDIR '/app'
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
ENV NODE_ENV 'production'
COPY nginx/default.conf /etc/nginx/conf.d/
CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'

COPY --from=builder /app/build /usr/share/nginx/html
